version: 2.1
jobs:
  build:
    macos:
      xcode: 13.4.1 

    steps:
      - checkout
      - run: pod install 
      - run: 
          name: Build and run tests
          command: fastlane scan 
          enviroment: 
            SCAN_DEVICE: iPhone 13 Pro max
            SCAN_SCHEME : Pokedex_ios

      - store_test_results:
          path: test_output
      - store_artifacts:
          path: test_output
          destination: scan-output
workflows:
  sample: 
    jobs:
      - build
