version: 2.1
jobs:
  build:
    macos:
      xcode: 13.4.1 # Specify the Xcode version 

    steps:
      - checkout
     # - run: pod install # Install CocoaPods dependencies
      - run: 
          name: Build and run tests
          command: fastlane scan 
          enviroment: 
            SCAN_DEVICE: iPhone 11 pro max
            SCAN_SCHEME : mvvm

      - store_test_results:
          path: test_output
      - store_artifacts:
          path: test_output
          destination: scan-output
workflows:
  sample: 
    jobs:
      - build